In [ ]:
import numpy as np


In [ ]:
# (5) random module

In [ ]:
# (5a). Randint() ---> random + integer
# it will create an array in which it will provide random numbers
# in a given range

In [ ]:
# stntax : np.random.Randint(min_number , max_number , total)

In [ ]:
a = np.random.Randint(1,10,3)
a

AttributeError: module 'numpy.random' has no attribute 'Randint'

In [ ]:
# (5b). seed() ---> it wil fix your ranom generTES data

In [ ]:
np.random.seed(78)
a = np.random.randint(1,10,3)
a

array([6, 7, 8])

In [ ]:
# (5c). rand() ---> it will generate num in  range 0-1

In [ ]:
a = np.random.rand(5)
a

array([0.5733576 , 0.59658201, 0.32560075, 0.76062093, 0.99367239])

In [ ]:
# (6). linespace(min,max,total_num)  --->
# it will create an array in  which it will provide same step num
# values in a given num

In [ ]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# 11-50 mid 4 random num genderate
# array ---> [7,7,7,7,7,7,7,7]
# 2-d [11-19] array ---> shape ,size , dim

In [ ]:
a = np.linspace(11,50,4)
a

array([11., 24., 37., 50.])

In [ ]:
a = [7,7,7,7,7,7,7,7]
a

[7, 7, 7, 7, 7, 7, 7, 7]

In [ ]:
a = np.array([ [11,19]])
a
print(a.shape)
print(a.size)
print(a.ndim)

(1, 2)
2
2


In [ ]:
# reshaping the array
# n(row) * n(col) = n(total elements)


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 ,4*3

In [ ]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])