In [1]:
import numpy as np

In [2]:
# view vs copy
# view means mdification in original data while copy means
# changs in duplicate data will not reflect original data

In [3]:
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
b = a[3:6]
b[:] = 0

In [5]:
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [6]:
# copy
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [7]:
b = a[3:6].copy()
b[:] = 0

In [8]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [9]:
# np.arange(min_num,max_num,step_num)---->

In [10]:
a = np.arange(1,10,3)
a

array([1, 4, 7])

In [11]:
a = np.arange(1,51,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [12]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [13]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [15]:
a+b   # 1+5 = 6  , 2+6 = 8,  4+8 =12

array([[ 6,  8],
       [10, 12]])

In [16]:
a- b

array([[-4, -4],
       [-4, -4]])

In [17]:
a.dot(b)     # for matrix multiplication

array([[19, 22],
       [43, 50]])

In [18]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [19]:
a**3

array([[ 1,  8],
       [27, 64]])

In [21]:
a = np.arange(1,10).reshape(3,3)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
print("total sum of matrix:",np.sum(a))
print("row wise sum  :",np.sum(a, axis=1))
print("col wise sum  :",np.sum(a, axis=0))

total sum of matrix: 45
row wise sum  : [ 6 15 24]
col wise sum  : [12 15 18]


In [25]:
# unique()---> it will remove duplicate element from array
# a ---> unique element array
# return_index = true ---> return indexing of unique element
# return_counts = true ---> total frequence of each unique item


In [26]:
a = np.array([1,2,2,3,2,4,4,4,4,4,4])
a

array([1, 2, 2, 3, 2, 4, 4, 4, 4, 4, 4])

In [27]:
np.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4]), array([0, 1, 3, 5]), array([1, 3, 1, 6]))

In [28]:
# horizontal and vartical scaling
# horizontal scaling means comnined 2 or more array in horizonatal
# and vartical scaling means combined 2 or more array in vartical


In [30]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [31]:
b= np.arange(5,9)
c = np.arange(9,13)

In [33]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a = np.arange(11,50,2.5)
a

array([11. , 13.5, 16. , 18.5, 21. , 23.5, 26. , 28.5, 31. , 33.5, 36. ,
       38.5, 41. , 43.5, 46. , 48.5])

In [59]:
b =a.reshape(4,4)

In [60]:

print("total sum of matrix:",np.sum(b))
print("row wise sum:",np.sum(b,axis=1))
print("col wise sum:",np.sum(b,axis=0))

total sum of matrix: 476.0
row wise sum: [ 59.  99. 139. 179.]
col wise sum: [104. 114. 124. 134.]
