In [1]:
# numpy --> numpy is an open source libery
#  which is used for scietific calculation


In [2]:
import numpy as np


In [3]:
a = [1,2,3,4]
type(a)

list

In [4]:
b = np.array(a)
b

array([1, 2, 3, 4])

In [5]:
type(b)

numpy.ndarray

In [6]:
b.ndim

1

In [7]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# matrix total element = n(rows)*n(columns)
# row_1 = [1,2,3]
# row_2 = [4,5,6]
# row_3 = [7,8,9]

# col_1 = [1,4,7]
# col_2 = [2,5,8]
# col_3 = [3,6,9]
# total_element = 3*3 = 9


In [16]:
print("total row and col:",b.shape) # shape = row ,col
print("total row:",b.shape[0])
print("total col:",b.shape[1])
print("total element in array:",b.size)   # size = row*col
print("total dimension:",b.ndim)       # dimension = 1d,2d,3d ...,nd

total row and col: (3, 3)
total row: 3
total col: 3
total element in array: 9
total dimension: 2


In [19]:
# diff between list and np.array

a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [20]:
a = np.array([1,2,3])
print(a)
print(a*3)

[1 2 3]
[3 6 9]


In [15]:
# pre-defined functon in numpy

In [21]:
# images ---> pixels ---> 0--255  ---> normalize ---> 0-1
# if i went to add black shadow then i have to use 0
# if i went to add black shadow then i have to use 0

In [22]:
# (1.) np.zeros() --> it will  create an array in which all the element will be 0 in either
# one dimension or multi-dimension

In [24]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [26]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# (2). ones() ---> it willit will  create an array in which all the element will be 1 in either
# one dimension or multi-dimension

In [30]:
a = np.ones((3))
a

array([1., 1., 1.])

In [31]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# (3). eye() ---> it will create an array in which we can set our custom values on
# digonal position

In [33]:
a = np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [34]:
b= np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])